### ISSUE TITLE
duplicated rows in the reference_atlas.csv

### ISSUE THREAD

**Issue by thaissabedot** [nloyfer/meth_atlas#1]
Some rows are duplicated in the reference_atlas.csv file. For example, the probe cg19442545 shows up 5 times with the same beta values across all the samples. Is it expected?

**Comment by nloyfer** [comment]
Yes. We included in this list all the CpGs that were selected as differential, as well as their neighboring CpGs. A duplicated site means it (or its neighbors) was among the top differential sites in multiple couples of cell types.

**Comment by thaissabedot** [comment]
I see, thank you.
