### ISSUE TITLE
Option to not show plot on screen

### ISSUE THREAD

**Issue by brucemoran** [nloyfer/meth_atlas#2]
Hi,

I am running iteratively across groups, but `deconvolve.py` with `--plot` plots to screen and so the iteration stops. Possible to allow `--plot` to just dump to png, not also to screen? Am I missing something?

Thanks,

Bruce.

**Comment by nloyfer** [comment]
You are right. I changed it per your request:
Now the png is being dumped in any case, and the `--plot` flag only triggers `plt.show()`, i.e displays the figure.

**Comment by brucemoran** [comment]
Thanks!
