### ISSUE TITLE
No fraction of tissue found in any samples...

### ISSUE THREAD

**Issue by brucemoran** [nloyfer/meth_atlas#3]
Hi,

running `deconvolve.pl` with prostate samples (benign and tumour, and cfDNA) shows no prostate in any. I also tested a tumour/normal sample from TCGA_PRAD (far right of image, prad_1, 2), which shows same profile. What is your take on this? NB I tried a few lung, colon samples and they seem to work, possibly this is prostate specific issue?

Thanks,

Bruce.

![1359_Perry_EPIC Roadmap450K TCGA_PRAD ra_deconv_plot](https://user-images.githubusercontent.com/7450546/57927743-e0a00b00-78a6-11e9-8e64-deadc7a48657.png)

**Comment by brucemoran** [comment]
Also from GSE108462, prostate Abiraterone study the data is similarly lacking in prostate.

![GSE108462 beta ra_deconv_plot](https://user-images.githubusercontent.com/7450546/57929510-73db3f80-78ab-11e9-897d-135a631fb867.png)

**Comment by brucemoran** [comment]
NB that we also find 0% prostate in the 554 patient TCGA PRAD dataset.

**Comment by nloyfer** [comment]
The problem was with the preprocessing.
It is best to preprocess the `IDAT` files using the same method used to generate our reference atlas. 
We have uploaded our [preprocessing script](https://github.com/nloyfer/meth_atlas/blob/master/pre_process/README.md#pre-processing) to this repository.
